title: SD INPRES SIHITE
description: 'Adik-adik silahkan melihat nilai masing-masing '
steps:
  - course: githubtraining/introduction-to-github
    description: Rangking
    title: Pilih sesuai nama masing-masing.
    link: Boy
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
